### ISSUE TITLE
Crumbs not showing up?

### ISSUE THREAD

**Issue by chrisgrieser** [tgrosinger/crumbs-obsidian#3]
**Describe the bug**
After installation, basically nothing shows up. Tried restarting Obsidian, too. Nothing in the console shows up related to crumbs.

**Screenshots**
not sure if relevant, but the row for Crumbs show no config options like other plugins do
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/73286100/209728921-0fd9b66d-8237-41e0-9548-fa55b3a4a8c5.png">

**Desktop (please complete the following information):**
```
macOS 13.0.1 (M1)
Obsidian 1.1.9
```

**Comment by tgrosinger** [comment]
This plugin has no settings. It also only displays the crumbs when you are viewing a note with a child. For example, open a note named `Hierarchy Test.Child One` and you should see the crumbs show up at the top. Let me know if that solves the issue for you.

**Comment by chrisgrieser** [comment]
Ah, I see!

Just watching the gif I thought the breadcrumbs are headings in a file, didn't notice that the breadcrumbs are based on file names instead. Yeah that clears it up.

**Comment by tgrosinger** [comment]
Let me know if there's something I could add to the readme that would make it more clear. Thank you 🙂
